name: Trigger Jenkins Build

on:
  push:
    branches:
      - master

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .env file from GitHub Secret
        run: echo "${{ secrets.MY_ENV_FILE }}" > .env

      - name: Set Slack Webhook URL
        run: echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Upload .env as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: envfile
          path: .env

      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB }}/build" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"
