name: Trigger Jenkins Build

on:
  push:
    branches:
      - master  # Trigger this workflow on push to master

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .env file from GitHub Secret
        run: echo "${{ secrets.MY_ENV_FILE }}" > .env

      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB }}/build" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"
